# Generated by Django 4.1.2 on 2022-10-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
